version: '2'
services:
    springboot_test2-mysql:
        container_name: springboot_test2-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/springboot_test2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=springboot_test2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
